= JAX-RS Analyzer Maven Plugin
Sebastian Daschner

Maven plugin for the https://github.com/sdaschner/jaxrs-analyzer[JAX-RS Analyzer].

To enable the plugin, simply add these lines to your pom.xml in the `<plugins>` section.

----
<plugin>
    <groupId>com.sebastian-daschner</groupId>
    <artifactId>jaxrs-analyzer-maven-plugin</artifactId>
    <version>0.5</version>
    <executions>
        <execution>
            <goals>
                <goal>analyze-jaxrs</goal>
            </goals>
            <configuration>
                <!-- Available backends are plaintext (default), swagger and asciidoc -->
                <backend>plaintext</backend>
                <!-- Domain of the deployed project, defaults to example.com -->
                <deployedDomain>example.com</deployedDomain>
            </configuration>
        </execution>
    </executions>
</plugin>
----

After building your project, the documentation resides under 'target/jaxrs-analyzer/'.

== Backends

=== Plain text

The plain text backend simply generates a test file with all REST resources.

=== Swagger

The swagger backend generates a swagger.json which can be loaded by the swagger-ui.

 Swagger UI is a dependency-free collection of HTML, Javascript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API.

=== AsciiDoc

AsciiDoc is a simple, human-readable lightweight markup language.
The generated AsciiDoc file can be easily processed (e.g. to HTML or PDF) by an AsciiDoc toolchain like https://github.com/asciidoctor/asciidoctor[Asciidoctor].
